---
deployment:
  tasks:
    - export DEPLOYPATH=/home/z16j1l9e4l18/public_html/kid-dev
    - export NODE_ENV=production
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R * $DEPLOYPATH
    - /bin/cp .next.config.ts $DEPLOYPATH 2>/dev/null || :
    - cd $DEPLOYPATH
    - npm ci --production=false
    - npm run build
    - /bin/mkdir -p tmp
    - touch tmp/restart.txt