---
deployment:
  tasks:
    - export DEPLOYPATH=/home/z16j1l9e4l18/public_html/kid-dev
    - export NODE_ENV=production
    - /bin/rm -rf $DEPLOYPATH
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R . $DEPLOYPATH
    - cd $DEPLOYPATH && npm install --production
    - cd $DEPLOYPATH && /bin/mkdir -p tmp && touch tmp/restart.txt