import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { Sidebar, SidebarContent, SidebarHeader, SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";

const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} antialiased w-[100vw] h-[100dvh] overflow-x-hidden`}
      >
        <SidebarProvider>
          <Sidebar>
            <SidebarContent>
              <SidebarHeader>
                <h2 className="text-lg font-semibold">Dashboard</h2>
              </SidebarHeader>
            </SidebarContent>
          </Sidebar>
          <main>
            <SidebarTrigger />
            {children}
          </main>

        </SidebarProvider>
        <Toaster />
      </body>
    </html>
  );
}
